### ISSUE TITLE
Not compatible with vagrant 1.1 plugins

### ISSUE THREAD

**Issue by moserke** [WinRb/vagrant-windows#20]
Vagrant 1.1 completely changed the plugin API.  Needs to be updated to work in that version.

http://docs.vagrantup.com/v2/plugins/index.html

**Comment by sneal** [comment]
I [migrated vagrant-windows](https://github.com/sneal/vagrant-windows/tree/vagrant-1.1-plugin-architecture) to the new Vagrant 1.1+ plugin architecture.

I still need to do some cleanup and testing, but it WOMM. I can successfully provision a Windows node using Vagrant 1.1.2 with the vagrant-windows plugin and the berkshelf plugin 1.0.6.

**Comment by Elufimov** [comment]
Maybe you place migration changes in to pull request?

**Comment by tsanders** [comment]
+1.  Please add ASAP.  Add to a pull request for your changes.

**Comment by sneal** [comment]
You can build the gem yourself from [my branch](https://github.com/sneal/vagrant-windows/tree/vagrant-1.1-plugin-architecture) in the mean time. At the very least the Puppet provisioning is broken and the readme is out of date. I'm going to attempt to address both of those before submitting a pull request.

Do we need/want to support both Vagrant 1.0 and 1.1+ at the same time?

**Comment by liamjbennett** [comment]
How are you installing your version of the plugin? Doing vagrant plugin install still installs 1.0.2

**Comment by Elufimov** [comment]
@liamjbennett With bundler
Gemfile

``` ruby
gem "vagrant-windows", :git => "git://github.com/sneal/vagrant-windows.git", :branch => "vagrant-1.1-plugin-architecture"
```

and then `bundle install`

**Comment by ndobson** [comment]
Also add this to your Gemfile

```
group :development do
# We depend on Vagrant for development, but we don't add it as a
# gem dependency because we expect to be installed within the
# Vagrant environment itself using `vagrant plugin`.
gem "vagrant", :git => "git://github.com/mitchellh/vagrant.git"
end
```

And this to your Vagranfile

```
Vagrant.require_plugin "vagrant-windows"
```

Then after 'bundle install'

```
bundle exec vagrant up
```

I have the plugin loading but winrm fails

```
bundle exec vagrant up
Bringing machine 'windowstest' up with 'virtualbox' provider...
[windowstest] Importing base box 'windows7'...
[windowstest] Matching MAC address for NAT networking...
[windowstest] Setting the name of the VM...
[windowstest] Clearing any previously set forwarded ports...
[windowstest] Creating shared folders metadata...
[windowstest] Clearing any previously set network interfaces...
[windowstest] Preparing network interfaces based on configuration...
[windowstest] Forwarding ports...
[windowstest] -- 22 => 2222 (adapter 1)
[windowstest] -- 3389 => 3390 (adapter 1)
[windowstest] -- 5985 => 5985 (adapter 1)
[windowstest] Booting VM...
[windowstest] Waiting for VM to boot. This can take a few minutes.
translation missing: en.vagrant_windows.errors.winrm_execution_error
```

**Comment by ndobson** [comment]
@sneal any idea why i'd be getting the above error?

**Comment by liamjbennett** [comment]
@ndobson why do we need to add vagrant to the gem file? vagrant is no longer disturbed that way.

@sneal I have added that to the Gemfile in my project (so it installs to my local gem installation) and that didn't work. I also created a Gemfile in the /Applications/Vagrant/embedded directory so that the gem was installed in the embedded ruby installation and that didn't work either. I am still getting the error that the "vagrant-windows" plugin could not be found.

**Comment by ndobson** [comment]
See the section at the bottom "Testing your plugin"
http://docs.vagrantup.com/v2/plugins/packaging.html

Vagrant supports that method for plugin testing/development... your other option is to run `rake build` within the vagrant-windows branch then `vagrant plugin install pkg/vagrant-windows-0.2.0.gem`

I prefer the first method because this branch seems to be very unstable and still needs work to be functional.

**Comment by sneal** [comment]
@ndobson I pushed some new changes. In particular I updated the readme.md and fixed the translation missing error you were getting.

**Comment by ndobson** [comment]
@sneal first, thanks for all your work on this.

I'm still getting an error when running `vagrant up`

Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'windows7'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[Berkshelf] Updating Vagrant's berkshelf: '/Volumes/Users/nick/.berkshelf/vagrant/berkshelf-20130410-44369-mqpnyj'
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 3389 => 3390 (adapter 1)
[default] -- 5985 => 5985 (adapter 1)
[default] Booting VM...
[default] Waiting for VM to boot. This can take a few minutes.
An error occurred executing a remote WinRM command.

Shell: powershell
Command: function which {
    $command = [Array](Get-Command $args[0] -errorAction continue)
    write-host  $command[0].Definition
}

function test ([Switch] $d, [String] $path) {
  Resolve-Path $path| Out-Null;
}

function chown {
  exit 0
}

function mkdir ([Switch] $p, [String] $path)
{
  if(Test-Path $path)
  {
    exit 0
  } else {
    New-Item $p -Type Directory -Force | Out-Null
  }
}

hostname
Message: HTTPClient::KeepAliveDisconnected

Here is my Vagrantfile:

Vagrant.configure("2") do |config|
    config.windows.halt_timeout = 15
    config.vm.box = "windows7"
    config.vm.guest = :windows
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"
    config.vm.provider "virtualbox" do |v|
       v.gui = true
    end
    config.vm.provision :chef_solo do |chef|
       chef.cookbooks_path = "../exosphere-chef-repo/cookbooks"
       chef.add_recipe "subversion::client"
    end
end

**Comment by sneal** [comment]
It looks like I may have broke the retry logic in the winrmcommunicator ready? method. Not sure why I've never seen this locally unless its a timing issue.

**Comment by ndobson** [comment]
Attaching debug output:

DEBUG winrmcommunicator: Creating WinRM session to http://localhost:5985/wsman with options: {:user=>"vagrant", :pass=>"vagrant", :host=>"localhost", :port=>5985, :operation_timeout=>1800, :basic_auth_only=>true}
ERROR warden: Error occurred: An error occurred executing a remote WinRM command.

Shell: powershell
Command: function which {
    $command = [Array](Get-Command $args[0] -errorAction continue)
    write-host  $command[0].Definition
}

function test ([Switch] $d, [String] $path) {
  Resolve-Path $path| Out-Null;
}

function chown {
  exit 0
}

function mkdir ([Switch] $p, [String] $path)
{
  if(Test-Path $path)
  {
    exit 0
  } else {
    New-Item $p -Type Directory -Force | Out-Null
  }
}

hostname
Message: HTTPClient::KeepAliveDisconnected
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: An error occurred executing a remote WinRM command.

Shell: powershell
Command: function which {
    $command = [Array](Get-Command $args[0] -errorAction continue)
    write-host  $command[0].Definition
}

function test ([Switch] $d, [String] $path) {
  Resolve-Path $path| Out-Null;
}

function chown {
  exit 0
}

function mkdir ([Switch] $p, [String] $path)
{
  if(Test-Path $path)
  {
    exit 0
  } else {
    New-Item $p -Type Directory -Force | Out-Null
  }
}

hostname
Message: HTTPClient::KeepAliveDisconnected
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x00000104969ad8
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
ERROR warden: Error occurred: An error occurred executing a remote WinRM command.

Shell: powershell
Command: function which {
    $command = [Array](Get-Command $args[0] -errorAction continue)
    write-host  $command[0].Definition
}

function test ([Switch] $d, [String] $path) {
  Resolve-Path $path| Out-Null;
}

function chown {
  exit 0
}

function mkdir ([Switch] $p, [String] $path)
{
  if(Test-Path $path)
  {
    exit 0
  } else {
    New-Item $p -Type Directory -Force | Out-Null
  }
}

hostname
Message: HTTPClient::KeepAliveDisconnected
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x000001048dbd78
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
ERROR warden: Error occurred: An error occurred executing a remote WinRM command.

Shell: powershell
Command: function which {
    $command = [Array](Get-Command $args[0] -errorAction continue)
    write-host  $command[0].Definition
}

function test ([Switch] $d, [String] $path) {
  Resolve-Path $path| Out-Null;
}

function chown {
  exit 0
}

function mkdir ([Switch] $p, [String] $path)
{
  if(Test-Path $path)
  {
    exit 0
  } else {
    New-Item $p -Type Directory -Force | Out-Null
  }
}

hostname
Message: HTTPClient::KeepAliveDisconnected
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x00000103256cb0
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Calling recover: #Vagrant::Action::Builtin::Call:0x00000103256d50
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #VagrantPlugins::ProviderVirtualBox::Action::Import:0x00000100bb9e40
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "1058bb93-411b-4290-940b-9fdd54854bdb", "--machinereadable"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="Vagrant-Win7_1365622948"
groups="/"
ostype="Windows 7 (64 bit)"
UUID="1058bb93-411b-4290-940b-9fdd54854bdb"
CfgFile="/Volumes/Users/nick/VirtualBox VMs/Vagrant-Win7_1365622948/Vagrant-Win7_1365622948.vbox"
SnapFldr="/Volumes/Users/nick/VirtualBox VMs/Vagrant-Win7_1365622948/Snapshots"
LogFldr="/Volumes/Users/nick/VirtualBox VMs/Vagrant-Win7_1365622948/Logs"
hardwareuuid="1058bb93-411b-4290-940b-9fdd54854bdb"
memory=512
pagefusion="off"
vram=24
cpuexecutioncap=100
hpet="off"
chipset="piix3"
firmware="BIOS"
cpus=1
synthcpu="off"
bootmenu="messageandmenu"
boot1="dvd"
boot2="disk"
boot3="none"
boot4="none"
acpi="on"
ioapic="on"
pae="off"
Time offset=0rtcuseutc="off"
hwvirtex="on"
hwvirtexexcl="off"
nestedpaging="on"
largepages="on"
vtxvpid="on"
VMState="running"
VMStateChangeTime="2013-04-10T19:42:31.554000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
storagecontrollername0="IDE Controller"
storagecontrollertype0="PIIX4"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="2"
storagecontrollerportcount0="2"
storagecontrollerbootable0="on"
storagecontrollername1="SATA Controller"
storagecontrollertype1="IntelAhci"
storagecontrollerinstance1="0"
storagecontrollermaxportcount1="30"
storagecontrollerportcount1="1"
storagecontrollerbootable1="on"
"IDE Controller-0-0"="none"
"IDE Controller-0-1"="none"
"IDE Controller-1-0"="emptydrive"
"IDE Controller-IsEjected"="off"
"IDE Controller-1-1"="none"
"SATA Controller-0-0"="/Volumes/Users/nick/VirtualBox VMs/Vagrant-Win7_1365622948/box-disk1.vmdk"
"SATA Controller-ImageUUID-0-0"="3ebbfe4b-50c3-429f-b964-8d375ac72d27"
natnet1="nat"
macaddress1="0800274A4FDC"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,,2222,,22"
Forwarding(1)="tcp_3390_3389,tcp,,3390,,3389"
Forwarding(2)="tcp_5985_5985,tcp,,5985,,5985"
nic2="none"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="usbtablet"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
lpt1="off"
lpt2="off"
audio="none"
clipboard="bidirectional"
draganddrop="disabled"
VideoMode="1024,768,32"
vrde="off"
usb="on"
ehci="off"
SharedFolderNameMachineMapping1="vagrant-root"
SharedFolderPathMachineMapping1="/Volumes/Users/nick/Projects/Vagrant-Win7"
SharedFolderNameMachineMapping2="v-csc-1"
SharedFolderPathMachineMapping2="/Volumes/Users/nick/.berkshelf/vagrant/berkshelf-20130410-45264-gmjvnz"
VRDEActiveConnection="off"
VRDEClients=0
GuestMemoryBalloon=0
GuestOSType="Windows7_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="4.1.18 r78361"
GuestAdditionsFacility_VirtualBox Base Driver=50,1365622959341
GuestAdditionsFacility_VirtualBox System Service=50,1365622972224
GuestAdditionsFacility_Seamless Mode=0,1365622959341
GuestAdditionsFacility_Graphics Mode=0,1365622959341
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: #Vagrant::Action::Builder:0x000001048d2f98
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantWindows::Errors::WinRMExecutionError: An error occurred executing a remote WinRM command.

Shell: powershell
Command: function which {
    $command = [Array](Get-Command $args[0] -errorAction continue)
    write-host  $command[0].Definition
}

function test ([Switch] $d, [String] $path) {
  Resolve-Path $path| Out-Null;
}

function chown {
  exit 0
}

function mkdir ([Switch] $p, [String] $path)
{
  if(Test-Path $path)
  {
    exit 0
  } else {
    New-Item $p -Type Directory -Force | Out-Null
  }
}

hostname
Message: HTTPClient::KeepAliveDisconnected>
ERROR vagrant: An error occurred executing a remote WinRM command.

Shell: powershell
Command: function which {
    $command = [Array](Get-Command $args[0] -errorAction continue)
    write-host  $command[0].Definition
}

function test ([Switch] $d, [String] $path) {
  Resolve-Path $path| Out-Null;
}

function chown {
  exit 0
}

function mkdir ([Switch] $p, [String] $path)
{
  if(Test-Path $path)
  {
    exit 0
  } else {
    New-Item $p -Type Directory -Force | Out-Null
  }
}

hostname
Message: HTTPClient::KeepAliveDisconnected
ERROR vagrant: /Volumes/Users/nick/.vagrant.d/gems/gems/vagrant-windows-0.2.0/lib/vagrant-windows/communication/winrmcommunicator.rb:199:in `rescue in shell_execute'
/Volumes/Users/nick/.vagrant.d/gems/gems/vagrant-windows-0.2.0/lib/vagrant-windows/communication/winrmcommunicator.rb:168:in`shell_execute'
/Volumes/Users/nick/.vagrant.d/gems/gems/vagrant-windows-0.2.0/lib/vagrant-windows/communication/winrmcommunicator.rb:72:in `block in execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/retryable.rb:17:in`retryable'
/Volumes/Users/nick/.vagrant.d/gems/gems/vagrant-windows-0.2.0/lib/vagrant-windows/communication/winrmcommunicator.rb:71:in `execute'
/Volumes/Users/nick/.vagrant.d/gems/gems/vagrant-windows-0.2.0/lib/vagrant-windows/communication/winrmcommunicator.rb:34:in`block in ready?'
/Applications/Vagrant/embedded/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
/Volumes/Users/nick/.vagrant.d/gems/gems/vagrant-windows-0.2.0/lib/vagrant-windows/communication/winrmcommunicator.rb:33:in`ready?'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/boot.rb:26:in `block in wait_for_boot'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/boot.rb:25:in`times'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/boot.rb:25:in `wait_for_boot'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/boot.rb:17:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/customize.rb:31:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/sane_defaults.rb:45:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/set_hostname.rb:16:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/forward_ports.rb:31:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/network.rb:105:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/share_folders.rb:20:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/clear_shared_folders.rb:12:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:11:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/nfs.rb:28:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/prune_nfs_exports.rb:15:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:106:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/env_set.rb:19:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:95:in`block in finalize_action'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/provision.rb:45:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:13:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/set_name.rb:35:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/check_accessible.rb:18:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in`block in run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in`run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in`busy'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in`block in run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in`run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:57:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builder.rb:109:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in`busy'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/machine.rb:129:in`action'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/up/command.rb:37:in `block in execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:182:in`block in with_target_vms'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:180:in `each'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:180:in`with_target_vms'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/up/command.rb:32:in `execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/cli.rb:46:in`execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/environment.rb:408:in `cli'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/bin/vagrant:75:in`<top (required)>'
/Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
/Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in`<main>'
 INFO interface: error: An error occurred executing a remote WinRM command.

Shell: powershell
Command: function which {
    $command = [Array](Get-Command $args[0] -errorAction continue)
    write-host  $command[0].Definition
}

function test ([Switch] $d, [String] $path) {
  Resolve-Path $path| Out-Null;
}

function chown {
  exit 0
}

function mkdir ([Switch] $p, [String] $path)
{
  if(Test-Path $path)
  {
    exit 0
  } else {
    New-Item $p -Type Directory -Force | Out-Null
  }
}

hostname
Message: HTTPClient::KeepAliveDisconnected
An error occurred executing a remote WinRM command.

Shell: powershell
Command: function which {
    $command = [Array](Get-Command $args[0] -errorAction continue)
    write-host  $command[0].Definition
}

function test ([Switch] $d, [String] $path) {
  Resolve-Path $path| Out-Null;
}

function chown {
  exit 0
}

function mkdir ([Switch] $p, [String] $path)
{
  if(Test-Path $path)
  {
    exit 0
  } else {
    New-Item $p -Type Directory -Force | Out-Null
  }
}

hostname
Message: HTTPClient::KeepAliveDisconnected

**Comment by ndobson** [comment]
Hey @sneal I figured out the issue....

On line 70 or winrmcommunicator.rb, you are retrying on the HTTPClient::KeepAliveDisconnected exception when in fact your shell_execute method is raising the Errors::WinRMExecutionError exception... change line 70 to this and the retries work as expected:

 exceptions = [Errors::WinRMExecutionError]

**Comment by ndobson** [comment]
Pull request submitted

**Comment by KAllan357** [comment]
I don't want to hijack this thread, but I am having an issue with @sneal's gem. Here's a gist: https://gist.github.com/KAllan357/5368817. 

I am going to assume that maybe this is because my box file has VirtualBox 4.1 Guest Additions and it can't mount the drives? I suppose that means I'll need to remake my box file with VBox 4.2 Guest Additions?

**Comment by sneal** [comment]
I see I'm missing a translation for en.vagrant.errors.winrm_bad_exit_status, but besides that I'm not sure why you're getting that failure. Did this used to work with Vagrant 1.0 and the old vagrant-windows gem?

I did make some changes around the windows guest configure_networks method that differs from VBox 4.1 to 4.2

``` ruby
        # The VBox driver 4.0 and 4.1 implement read_mac_addresses, but 4.2 does not?
        begin
          driver_mac_address = @machine.provider.driver.read_mac_addresses.invert
        rescue NoMethodError
          driver_mac_address = {}
          driver_mac_address[@machine.provider.driver.read_mac_address] = "macaddress1"
        end
```

**Comment by liamjbennett** [comment]
@KAllan357 it's not just you. I am getting the same error.

**Comment by sneal** [comment]
@KAllan357 @liamjbennett Assuming the issue is specific to VBox 4.0/4.1 can you try [this branch](https://github.com/sneal/vagrant-windows/tree/vagrant-1.1-plugin-architecture-vbox4.1)? I removed the code that was different between 4.2 and 4.0/4.1.

If that doesn't work can you send me a gist with the debug Vagrant log output?

**Comment by sneal** [comment]
Anyone want to try out the Puppet support? I just pushed changes that load the Puppet provisioner, but I haven't had time to install or learn about Puppet to try it out.

**Comment by kgsharp** [comment]
tried this with the branch codeline and vagrant 1.1, but I am getting the following (may just be vmware_fusion plugin having issues talking to vagrant-windows plugin)? 

vagrant plugin list
vagrant-vmware-fusion (0.4.2)
vagrant-windows (0.2.0)

Bringing machine 'default' up with 'vmware_fusion' provider...
[default] Verifying vmnet devices are healthy...
[default] Preparing network adapters...
[default] Fixed port collision for 22 => 2222. Now on port 2200.
[default] Starting the VMware VM...
[default] Waiting for the VM to finish booting...
/Applications/Vagrant/embedded/lib/ruby/1.9.1/timeout.rb:54:in `timeout': undefined method`zero?' for #Object:0x00000100c92da8 (NoMethodError)
    from /Users/user/.vagrant.d/gems/gems/vagrant-windows-0.2.0/lib/vagrant-windows/communication/winrmcommunicator.rb:33:in `ready?'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:45:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:260:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:106:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:804:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:1071:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/set_hostname.rb:16:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:556:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:899:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:133:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:751:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/nfs.rb:28:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:852:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/provision.rb:45:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/lock.rb:51:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in`block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in`run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:80:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:830:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in`busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:986:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in`block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in`run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:986:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/lock.rb:42:in `block in call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/lock.rb:27:in`open'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/lock.rb:27:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
    from /Users/user/.vagrant.d/gems/gems/vagrant-vmware-fusion-0.4.2/lib/vagrant-vmware-fusion/action_farm.rb:108:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builder.rb:109:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in`block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in`run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/machine.rb:129:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/up/command.rb:37:in`block in execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:182:in `block in with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:180:in`each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:180:in `with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/up/command.rb:32:in`execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/cli.rb:46:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/environment.rb:408:in`cli'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/bin/vagrant:75:in `<top (required)>'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in`load'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'

**Comment by pmorton** [comment]
@sneal  Would you mind doing a pull request on this one. It seems that you have done the hard work here.

**Comment by juliandunn** [comment]
+1 to just committing this from @sneal 's branch

**Comment by sneal** [comment]
Opened pull request #27

**Comment by pmorton** [comment]
@sneal wanna do the honors of closing this?
